language: csharp
os: linux
dist: bionic
env:
    global:
        - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
        - DOTNET_CLI_TELEMETRY_OPTOUT=1
mono: none
dotnet: 2.2
script:
    - dotnet build ./aardvark.docs.sln