image:
    - Visual Studio 2019
    - Ubuntu
skip_branch_with_pr: true
environment:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
build_script:
    - build.cmd

for:
-
  matrix:
    only:
      - image: Ubuntu
  build_script:
  - ./build.sh