name: Windows

on: 
  push:
    paths-ignore:
    - 'README.md'
  pull_request:
    paths-ignore:
    - 'README.md'
    
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.100'
    - name: Build
      run: .\build.cmd
